### PR TITLE
Frontend/Backend testing framework

### PR DESCRIPTION
**Pull request by jeffreyquiambao**
- Jest testing framework for frontend and backend
- Frontend render testing for the Landing and Join components
- Backend tests for addUser and addHost

### CODE REVIEW

**Review by dlhxu — APPROVED** [review]
Looks good. Selecting the same framework to test backend and frontend will help keep our testing approach consistent and easy to understand

**Review by varoongupta — APPROVED** [review]
looks good!

**Review by billxsheng — APPROVED** [review]
Good job picking consistent testing frameworks.

**Review by rosakng — APPROVED** [review]
amazing!!

**Pull request merged**
