### PR TITLE
Non story task: fix UI on swiping container

### PR DESCRIPTION
**Pull request by rosakng**
image

- added react strap dependency
- centered UI
- fixed mismatch color on buttons and made buttons larger
- replaced all icons with material UI icons
- added border

### CODE REVIEW

**Comment by varoongupta** [comment]
way to go dude

**Review by varoongupta — APPROVED** [review]
nice stuff!

**Review by billxsheng — APPROVED** [review]
Looks good!

**Review by jeffreyquiambao — APPROVED** [review]

**Review by dlhxu — APPROVED** [review]
Looking good!

**Pull request merged**
